from selenium.webdriver.common.by import By

class Locators:
    login_button = (By.XPATH, "//button[text()='Вход и регистрация']")
    logout_button = (By.XPATH, "//button[text()='Выйти']")
    no_account_button = (By.XPATH, "//button[text()='Нет аккаунта']")
    create_account_button = (By.XPATH, "//button[text()='Создать аккаунт']")
    main_login_button = (By.XPATH, "//button[text()='Войти']")
    error_text = (By.CLASS_NAME, 'input_span__yWPqB')
    error_border = (By.CLASS_NAME, 'input_inputError__fLUP9')
    email_field = (By.NAME, "email")
    password_input = (By.NAME, "password")
    repeat_password_field = (By.NAME, "submitPassword")
    email_container = (By.XPATH, "//input[@name='email']/ancestor::div[contains(@class, 'input_inputError__fLUP9')]")
    password_error_container = (By.XPATH, "//input[@name='password']/ancestor::div[contains(@class, 'input_inputError__fLUP9')]")
    confirm_password_container = (By.XPATH, "//input[@name='submitPassword']/ancestor::div[contains(@class, 'input_inputError__fLUP9')]")
    my_ads_section = (By.CLASS_NAME, "profile_profile__bixlA")
    user_text = (By.XPATH, "//h3[text()='User.']")
    user_avatar = (By.CLASS_NAME, 'svgSmall')
    user_profile_button = (By.XPATH, '//button[@class="circleSmall"]')
    add_item = (By.CLASS_NAME, 'picture')
    create_add_button = (By.XPATH, "//button[text()='Разместить объявление']")
    auth_required_text = (By.XPATH, "//h1[text()='Чтобы разместить объявление, авторизуйтесь']")
    add_name_field = (By.NAME, "name")
    add_description_field = (By.XPATH, "//textarea[@class='textarea_inputStandart__IoNxq spanGlobal']")
    add_price_field = (By.NAME, "price")
    category_dropdown = (By.XPATH, "//button[contains(@class, 'dropDownMenu_arrowDown__pfGL1')]")
    category_option = (By.XPATH, "//button[@class='dropDownMenu_btn__o8ARs dropDownMenu_noDefault__wSKsP']")
    condition_selector = (By.CLASS_NAME, "radioUnput_shell__Wtdwe")
    city_dropdown = (By.XPATH, "//input[@name='city']/following-sibling::button")
    city_option = (By.XPATH, "//button/span[text()='Санкт-Петербург']/parent::button")
    publish_button = (By.XPATH, "//button[text()='Опубликовать']")

